#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

STACK_SIZE="$1"

if [ "x$STACK_SIZE" = "x" ]
then
  STACK_SIZE="0x80000"
fi

OUTPUT_DIR="$2"
if [ "x$OUTPUT_DIR" = "x" ]
then
  OUTPUT_DIR="."
fi
OUTPUT_DIR=$(realpath $OUTPUT_DIR)

sed s/@@STACK_SIZE@@/$STACK_SIZE/g $SCRIPT_DIR/ld_interface.ld.template > $OUTPUT_DIR/ld_interface.ld
sed s/@@STACK_SIZE@@/$STACK_SIZE/g $SCRIPT_DIR/bootloader.S.template > $OUTPUT_DIR/bootloader.S
